"""init

Revision ID: 597bd0688fb4
Revises: 
Create Date: 2026-06-17 15:05:18.583880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '597bd0688fb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # chunks.embedding below needs pgvector; migrations run as a role that may create it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession')
    )
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_ticker'), 'hypotheses', ['ticker'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('robinhood_token_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context_blurb', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_filing_id'), 'chunks', ['filing_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('critic_verdict', sa.JSON(), nullable=False),
    sa.Column('guardrail', sa.JSON(), nullable=False),
    sa.Column('human_decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    op.create_table('diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('cur_accession', sa.String(length=32), nullable=False),
    sa.Column('prior_accession', sa.String(length=32), nullable=False),
    sa.Column('semantic_drift', sa.Float(), nullable=False),
    sa.Column('lexical_change', sa.Float(), nullable=False),
    sa.Column('added', sa.JSON(), nullable=False),
    sa.Column('removed', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cur_accession'], ['filings.accession'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diffs_ticker'), 'diffs', ['ticker'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('forward_return', sa.Float(), nullable=True),
    sa.Column('spy_return', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_order_id'), 'outcomes', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_order_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_table('orders')
    op.drop_index(op.f('ix_diffs_ticker'), table_name='diffs')
    op.drop_table('diffs')
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_chunks_filing_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('users')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_hypotheses_ticker'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
